### ISSUE TITLE
Run tests via GitHub Actions on pull requests

### ISSUE THREAD

**Issue by DivineDominion** [CleanCocoa/DeclarativeTextKit#3]
While I'm working on this locally, I run unit tests compulsively all the time.

For PR's, we better double-check with CI like GitHub Actions.

**Comment by ikelax** [comment]
I want to work on this. Do you already have further steps in mind?

**Comment by DivineDominion** [comment]
Nothing special. There are GitHub action templates that should do the trick. For now, we should end up running `swift test`. That'll compile and run tests and report the result.

Once other platforms are introduced in e.g. #2 we would need to create a "test matrix". But we'll figure that out once we get there.

**Comment by DivineDominion** [comment]
@ikelax You can take liberal inspiration from https://github.com/ChimeHQ/ChimeKit -- and if the Actions work, also uncomment the "Build" badge in the `README` that I prepared.
